version: "3.9"
services:
  puc-schedule-sms:
    container_name: "puc-schedule-sms"
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      # web
      - traefik.http.routers.untpuc-http.rule=Host(`untpuc.localhost`)
      - traefik.http.routers.untpuc-http.entrypoints=web
      - traefik.http.routers.untpuc-http.middlewares=force-https
      # websecure
      - traefik.http.routers.untpuc-https.rule=Host(`untpuc.localhost`)
      - traefik.http.routers.untpuc-https.entrypoints=websecure
      - traefik.http.services.untpuc-https.loadbalancer.server.port=3110
      - traefik.http.routers.untpuc-https.tls=true
      - traefik.http.routers.untpuc-https.tls.certresolver=leprod
    environment:
      - NODE_ENV=production
      - DATABASE_URL
      - PORT=3110
      - SMS_API_KEY
      - SMS_SENDER=UNTPUU
      - TELEGRAM_BOT_TOKEN
      - JWT_SECRET
    networks:
      - internal-net
    restart: unless-stopped
networks:
  internal-net:
    name: fury-net
    external: true